x-dev-volumes: &dev-volumes
  - ../agents:/workspace/double_pendulum/agents
  - ../config:/workspace/double_pendulum/config
  - ../envs:/workspace/double_pendulum/envs
  - ../scripts:/workspace/double_pendulum/scripts
  - ../urdf:/workspace/double_pendulum/urdf
  - ../utils:/workspace/double_pendulum/utils

services:
  train:
    volumes: *dev-volumes
  eval:
    volumes: *dev-volumes
  play:
    volumes: *dev-volumes
  keyboard:
    volumes: *dev-volumes
  shell:
    volumes: *dev-volumes
